server:
  port: 9000

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.60.204:8848
        namespace: 2975f69b-b4a8-44cd-bd1b-277c5485eaed
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: content-service
          uri: lb://content-service
          predicates:
            - Path=/content/**
